name: .NET

on:
  push:
    branches: [ "master" ]
    tags: [ "*" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0 # avoid shallow clone

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Pack
      run: dotnet pack -c Release -o out -p:ContinuousIntegrationBuild=true

    - name: Push
      run: dotnet nuget push *.nupkg -s nuget.org -k $NUGET_API_KEY
      if: startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master'
      working-directory: out
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
